// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4cuV17cRfwPcuutsN-jvJZmUe4bCJuLU',
    appId: '1:382000129033:web:62bb6ad37e4e81c024c4d8',
    messagingSenderId: '382000129033',
    projectId: 'partidos-app-e50f7',
    authDomain: 'partidos-app-e50f7.firebaseapp.com',
    storageBucket: 'partidos-app-e50f7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOuHuthcatIbRx60f3O0hDQshh_E9wnRI',
    appId: '1:382000129033:android:0be84b898cedc86a24c4d8',
    messagingSenderId: '382000129033',
    projectId: 'partidos-app-e50f7',
    storageBucket: 'partidos-app-e50f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuxhobKXyfAOgYO9q7s91rnaE73d8LkcA',
    appId: '1:382000129033:ios:07398eebab68e80624c4d8',
    messagingSenderId: '382000129033',
    projectId: 'partidos-app-e50f7',
    storageBucket: 'partidos-app-e50f7.appspot.com',
    iosClientId: '382000129033-8n6535qft9d8hakuabtn4ogg55mrnnqb.apps.googleusercontent.com',
    iosBundleId: 'com.example.politicalPartiesBrazil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuxhobKXyfAOgYO9q7s91rnaE73d8LkcA',
    appId: '1:382000129033:ios:07398eebab68e80624c4d8',
    messagingSenderId: '382000129033',
    projectId: 'partidos-app-e50f7',
    storageBucket: 'partidos-app-e50f7.appspot.com',
    iosClientId: '382000129033-8n6535qft9d8hakuabtn4ogg55mrnnqb.apps.googleusercontent.com',
    iosBundleId: 'com.example.politicalPartiesBrazil',
  );
}
